name: Build
on:
  push:
    tags:
      - '*'
jobs:
  macOS:
    runs-on: macos-10.15
    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: mkdir -p msgpack-c/lib
      - name: make
        working-directory: msgpack-c/lib
        run: |
          cmake ..
          clang -Wall -O3 -DNDEBUG -g0 ../src/* -I./include -I./include/msgpack -I../include -I../include/msgpack -shared -o libmsgpackc.2.0.0.dylib -arch arm64 -arch x86_64
      - run: tar czf msgpack-c.tgz msgpack-c/lib/*.dylib msgpack-c/include/ msgpack-c/COPYING
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: msgpack-c.tgz
          asset_name: msgpack-c-macos.tgz
          tag: ${{ github.ref }}
          overwrite: true
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: mkdir -p msgpack-c/lib
      - name: make
        working-directory: msgpack-c/lib
        run: |
          cmake ..
          make
      - run: tar czf msgpack-c.tgz msgpack-c/lib/libmsgpackc.so* msgpack-c/include/ msgpack-c/COPYING
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: msgpack-c.tgz
          asset_name: msgpack-c-linux.tgz
          tag: ${{ github.ref }}
          overwrite: true
  mingw-w64:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install mingw-w64
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: mkdir -p msgpack-c/lib
      - name: make
        working-directory: msgpack-c/lib
        run: |
          cmake ..
          x86_64-w64-mingw32-gcc -Wall -s -Os -DNDEBUG -g0 ../src/* -I./include -I./include/msgpack -I../include -I../include/msgpack -shared -o libmsgpackc.dll
      - run: tar czf msgpack-c.tgz msgpack-c/lib/libmsgpackc.dll msgpack-c/include/ msgpack-c/COPYING
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: msgpack-c.tgz
          asset_name: msgpack-c-x86_64-w64-mingw32.tgz
          tag: ${{ github.ref }}
          overwrite: true
