name: Build
on:
  push:
    tags:
      - '*'
jobs:
  macOS:
    runs-on: macos-10.15
    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: compile
        working-directory: ./msgpack-c
        run: cmake .
        run: make
        run: tar czf msgpack-c.tgz *.dylib include/ COPYING
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: msgpack-c/msgpack-c.tgz
          asset_name: msgpack-c-macos.tgz
          tag: ${{ github.ref }}
          overwrite: true
