name: Build
on:
  push:
    tags:
      - '*'
jobs:
  macOS:
    runs-on: macos-10.15
    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: cmake
        working-directory: ./msgpack-c
        run: cmake .
      - name: make
        working-directory: ./msgpack-c
        run: clang -Wall -s -Os -DNDEBUG -g0 src/* -I./include -I./include/msgpack -shared -o libmsgpackc.2.0.0.dylib -arch arm64 -arch x86_64
      - name: archive
        run: tar czf msgpack-c.tgz msgpack-c/*.dylib msgpack-c/include/ msgpack-c/COPYING
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: msgpack-c.tgz
          asset_name: msgpack-c-macos.tgz
          tag: ${{ github.ref }}
          overwrite: true
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: cmake
        working-directory: ./msgpack-c
        run: cmake .
      - name: make
        working-directory: ./msgpack-c
        run: make
      - name: archive
        run: tar czf msgpack-c.tgz msgpack-c/libmsgpackc.so* msgpack-c/include/ msgpack-c/COPYING
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: msgpack-c.tgz
          asset_name: msgpack-c-linux.tgz
          tag: ${{ github.ref }}
          overwrite: true
  mingw-w64:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install mingw-w64
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: cmake
        working-directory: ./msgpack-c
        run: cmake .
      - name: compile
        working-directory: ./msgpack-c
        run: x86_64-w64-mingw32-gcc -Wall -s -Os -DNDEBUG -g0 src/* -I./include -I./include/msgpack -shared -o libmsgpackc.dll
      - name: archive
        run: tar czf msgpack-c.tgz msgpack-c/libmsgpackc.dll msgpack-c/include/ msgpack-c/COPYING
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: msgpack-c.tgz
          asset_name: msgpack-c-x86_64-w64-mingw32.tgz
          tag: ${{ github.ref }}
          overwrite: true
